project:
  type: website

website:
  title: "Taller EPH en R - UBA Sociales"
  navbar:
    background: "#973267"
    right:
      - href: index.qmd
        text: "Inicio"
      - text: "Equipo"
        file: Equipo.qmd
      - text: "Slides"
        file: slides.html
      - text: "Práctica"
        file: Tallereph01.html

    tools:
      - icon: github
        href: https://github.com/SoyAndrea/tallerEPH



format:
  html:
    theme: minty
    css: styles.css
    toc: true
    lang: es

editor: visual

